use_cnt: 4
Tag:
- no: 0
  address: 0
  use: true
  gui_display: true
  type: 
  name: ''
  description: ''
  etc: ''
  value_raw: 0
  value: 0
  min: 0
  max: 0
  range_row: 0
  range_high: 0
  gain: 0
  offset: 0
  unit: 4~20mA
  range: _4_to_20_ma
- no: 0
  address: 1
  use: true
  gui_display: true
  type: 
  name: ''
  description: ''
  etc: ''
  value_raw: 0
  value: 0
  min: 0
  max: 0
  range_row: 0
  range_high: 0
  gain: 0
  offset: 0
  unit: 4~20mA
  range: _4_to_20_ma
- no: 0
  address: 2
  use: true
  gui_display: true
  type: 
  name: ''
  description: ''
  etc: ''
  value_raw: 0
  value: 0
  min: 0
  max: 0
  range_row: 0
  range_high: 0
  gain: 0
  offset: 0
  unit: 4~20mA
  range: _4_to_20_ma
- no: 0
  address: 3
  use: true
  gui_display: true
  type: 
  name: ''
  description: ''
  etc: ''
  value_raw: 0
  value: 0
  min: 0
  max: 0
  range_row: 0
  range_high: 0
  gain: 0
  offset: 0
  unit: 4~20mA
  range: _4_to_20_ma
