step_cnt: 3
ccss_cnt: 2
mixing_use: true
matching_file: ''
refill_use: true
refill_ccss: CCSS1
ccss_info:
- name: LAL
  use: true
  ccss_row: 1
  type: CCSS1
  chemical: LAL
- name: DIW
  use: true
  ccss_row: 1
  type: CCSS4
  chemical: DIW
step_info:
- name: Not Use
  use: true
- name: Step 1
  use: true
- name: Step 2
  use: true
mixing_data:
- 0
- 1
- 1
- 0
- 0
- 0
