use_cnt: 70
Tag:
- no: 0
  address: 0
  use: true
  gui_display: true
  name: EMS
  description: EMS
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 1
  address: 1
  use: true
  gui_display: true
  name: E_RIGHT_DOOR
  description: E_RIGHT_DOOR
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 2
  address: 2
  use: false
  gui_display: true
  name: ELEC_DOOR_OVERRIDE
  description: ELEC_DOOR_OVERRIDE
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:40:48.0789353+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 3
  address: 2
  use: true
  gui_display: false
  name: GPS_UPS_TRIP
  description: GPS_UPS_TRIP
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:40:48.0789353+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 4
  address: 4
  use: false
  gui_display: false
  name: HDIW_POWER_ON
  description: HDIW_POWER_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 5
  address: 5
  use: false
  gui_display: false
  name: HDIW_REMOTE_MODE
  description: HDIW_REMOTE_MODE
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 6
  address: 6
  use: false
  gui_display: false
  name: HDIW_TOTAL_ALARM
  description: HDIW_TOTAL_ALARM
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 7
  address: 7
  use: false
  gui_display: false
  name: MAIN_UNIT_MIX_TRIP
  description: MAIN_UNIT_MIX_TRIP
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 8
  address: 8
  use: false
  gui_display: false
  name: LEFT_FAN_ALARM
  description: LEFT_FAN_ALARM
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 9
  address: 9
  use: false
  gui_display: false
  name: RIGHT_FAN_ALARM
  description: RIGHT_FAN_ALARM
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 10
  address: 10
  use: false
  gui_display: false
  name: SUPPLY_A_HEATER_DRAIN_V_V
  description: SUPPLY_A_HEATER_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 11
  address: 11
  use: false
  gui_display: false
  name: SUPPLY_B_HEATER_DRAIN_V_V
  description: SUPPLY_B_HEATER_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 12
  address: 12
  use: false
  gui_display: false
  name: Drain_Pump_On_Level
  description: Drain_Pump_On_Level
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 13
  address: 13
  use: false
  gui_display: false
  name: SPARE_13
  description: SPARE_13
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 14
  address: 14
  use: false
  gui_display: false
  name: SPARE_14
  description: SPARE_14
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 15
  address: 15
  use: false
  gui_display: false
  name: SPARE_15
  description: SPARE_15
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 16
  address: 16
  use: false
  gui_display: false
  name: SPARE_16
  description: SPARE_16
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:19:23.2976127+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 17
  address: 17
  use: false
  gui_display: false
  name: SPARE_17
  description: SPARE_17
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:19:23.2976127+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 18
  address: 18
  use: false
  gui_display: false
  name: SPARE_18
  description: SPARE_18
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 19
  address: 19
  use: false
  gui_display: false
  name: SPARE_19
  description: SPARE_19
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 20
  address: 16
  use: true
  gui_display: true
  name: TANKA_LEVEL_HH
  description: TANKA_LEVEL_HH
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:19:23.2976127+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 21
  address: 17
  use: true
  gui_display: true
  name: TANKA_OVERFLOW_CHECK
  description: TANKA_OVERFLOW_CHECK
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:19:23.2976127+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 22
  address: 22
  use: false
  gui_display: false
  name: TANKB_LEVEL_HH
  description: TANKB_LEVEL_HH
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 23
  address: 23
  use: false
  gui_display: false
  name: TANKB_OVERFLOW_CHECK
  description: TANKB_OVERFLOW_CHECK
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 24
  address: 20
  use: true
  gui_display: true
  name: BOTTOM_VAT_LEAK1
  description: BOTTOM_VAT_LEAK1
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:46:42.3396769+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 25
  address: 25
  use: false
  gui_display: false
  name: Drain_Tank_H
  description: Drain_Tank_H
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 26
  address: 26
  use: false
  gui_display: false
  name: TANK_VAT_LEAK
  description: TANK_VAT_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 27
  address: 24
  use: true
  gui_display: true
  name: DIKE_LEAK
  description: DIKE_LEAK
  etc: 
  unit: N.C
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 28
  address: 28
  use: true
  gui_display: true
  name: C_DOOR_ALARM
  description: C_DOOR_ALARM
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 29
  address: 29
  use: true
  gui_display: true
  name: EXH_LL
  description: EXH_LL
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 30
  address: 30
  use: false
  gui_display: false
  name: SPARE_30
  description: SPARE_30
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 31
  address: 31
  use: true
  gui_display: true
  name: MAIN_EQ_TRIP
  description: MAIN_EQ_TRIP
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 2022-12-14T13:19:23.2976127+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 32
  address: 32
  use: true
  gui_display: true
  name: TANKA_LEVEL_H
  description: TANKA_LEVEL_H
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 2022-12-12T16:17:37.6230463+09:00
- no: 33
  address: 33
  use: true
  gui_display: true
  name: TANKA_LEVEL_M
  description: TANKA_LEVEL_M
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 2022-12-14T13:46:42.3396769+09:00
- no: 34
  address: 34
  use: true
  gui_display: true
  name: TANKA_LEVEL_L
  description: TANKA_LEVEL_L
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 2022-12-14T13:46:42.3396769+09:00
- no: 35
  address: 35
  use: true
  gui_display: true
  name: TANKA_LEVEL_LL
  description: TANKA_LEVEL_LL
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2022-12-12T16:31:50.6928088+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 36
  address: 36
  use: true
  gui_display: true
  name: TANKA_EMPTY_CHECK
  description: TANKA_EMPTY_CHECK
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2022-12-12T16:06:16.3107032+09:00
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 37
  address: 37
  use: false
  gui_display: false
  name: TANKB_LEVEL_H
  description: TANKB_LEVEL_H
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 38
  address: 38
  use: false
  gui_display: false
  name: TANKB_LEVEL_M
  description: TANKB_LEVEL_M
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 39
  address: 39
  use: false
  gui_display: false
  name: TANKB_LEVEL_L
  description: TANKB_LEVEL_L
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 40
  address: 40
  use: false
  gui_display: false
  name: TANKB_LEVEL_LL
  description: TANKB_LEVEL_LL
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 41
  address: 41
  use: false
  gui_display: false
  name: TANKB_EMPTY_CHECK
  description: TANKB_EMPTY_CHECK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 42
  address: 42
  use: false
  gui_display: false
  name: SPARE_42
  description: SPARE_42
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 43
  address: 43
  use: false
  gui_display: false
  name: RETURN_DRAIN_V_V
  description: RETURN_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 44
  address: 44
  use: false
  gui_display: false
  name: SPARE_44
  description: SPARE_44
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 45
  address: 45
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_LEFT_ON
  description: CIRCULATION_PUMP_LEFT_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 46
  address: 46
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_RIGHT_ON
  description: CIRCULATION_PUMP_RIGHT_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 47
  address: 47
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_LEAK
  description: CIRCULATION_PUMP_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 48
  address: 48
  use: false
  gui_display: false
  name: SPARE_48
  description: SPARE_48
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 49
  address: 49
  use: false
  gui_display: false
  name: SPARE_49
  description: SPARE_49
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 50
  address: 50
  use: false
  gui_display: false
  name: SPARE_50
  description: SPARE_50
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 51
  address: 23
  use: true
  gui_display: true
  name: Gas_Detec_Alarm
  description: Gas_Detec_Alarm
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 52
  address: 25
  use: true
  gui_display: true
  name: Purge_Unit_Alarm
  description: Purge_Unit_Alarm
  etc: 
  unit: N.C
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 53
  address: 27
  use: true
  gui_display: true
  name: LEAK_FAULT
  description: LEAK_FAULT
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2022-12-14T15:03:18.3585746+09:00
- no: 54
  address: 37
  use: true
  gui_display: true
  name: Purge_Unit_OK
  description: Purge_Unit_OK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 55
  address: 55
  use: false
  gui_display: false
  name: CM_DRAIN_PUMP_ON_LEVEL
  description: CM_DRAIN_PUMP_ON_LEVEL
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 56
  address: 56
  use: false
  gui_display: false
  name: CM_LEAK
  description: CM_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 57
  address: 57
  use: false
  gui_display: false
  name: CM_DIKE_LEAK
  description: CM_DIKE_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 58
  address: 58
  use: false
  gui_display: false
  name: CM_VAT_LEAK
  description: CM_VAT_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 59
  address: 59
  use: false
  gui_display: false
  name: CM_DRAIN_TANK_H
  description: CM_DRAIN_TANK_H
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 60
  address: 60
  use: false
  gui_display: false
  name: SPARE_60
  description: SPARE_60
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 61
  address: 61
  use: false
  gui_display: false
  name: SPARE_61
  description: SPARE_61
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 62
  address: 62
  use: false
  gui_display: false
  name: SPARE_62
  description: SPARE_62
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 63
  address: 63
  use: false
  gui_display: false
  name: SPARE_63
  description: SPARE_63
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 64
  address: 64
  use: false
  gui_display: false
  name: SPARE_64
  description: SPARE_64
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 65
  address: 65
  use: false
  gui_display: false
  name: SPARE_65
  description: SPARE_65
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 66
  address: 66
  use: false
  gui_display: false
  name: SPARE_66
  description: SPARE_66
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 67
  address: 67
  use: false
  gui_display: false
  name: SPARE_67
  description: SPARE_67
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 68
  address: 68
  use: false
  gui_display: false
  name: SPARE_68
  description: SPARE_68
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 69
  address: 69
  use: false
  gui_display: false
  name: SPARE_69
  description: SPARE_69
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2022-12-14T15:03:18.3585746+09:00
  dt_on: 0001-01-01T00:00:00.0000000
