db:
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: ctc
  table: alarm_logs
  field: alarm_occurred_time
  date: 250
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
