db:
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 16
- database: cds
  table: event_logs
  field: event_occurred_time
  date: 30
- database: cds
  table: totalusage_logs
  field: totalusage_saved_time
  date: 30
- database: ''
  table: ''
  field: alarm_occurred_time
  date: 90
- database: ''
  table: ''
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
