db:
- database: cds
  table: alarm_logs
  field: alarm_occurred_time
  date: 90
- database: cds
  table: event_logs
  field: event_occurred_time
  date: 90
- database: cds
  table: totalusage_logs
  field: totalusage_saved_time
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
- database: cds
  table: 
  field: 
  date: 90
