log:
- path: D:\CDS\Log\
  date: 60
- path: cds
  date: 90
- path: cds
  date: 30
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
- path: cds
  date: 90
