use_cnt: 10
Tag:
- address: 0
  use: true
  gui_display: false
  comport: 7
  name: 
  description: SCR
  etc: 
  ch_total_cnt: 4
  unit: SCR_DPU31A_025A
  buadrate: _38400
  parity: even
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 1
  use: true
  gui_display: false
  comport: 10
  name: 
  description: TEMP LIMIT
  etc: 
  ch_total_cnt: 1
  unit: TEMP_CONTROLLER_M74R
  buadrate: _19200
  parity: even
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 2
  use: false
  gui_display: false
  comport: 62
  name: 
  description: Spare
  etc: 
  ch_total_cnt: 0
  unit: THERMOSTAT_HE_3320C
  buadrate: _9600
  parity: none
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 3
  use: true
  gui_display: false
  comport: 23
  name: 
  description: USF-500 FLOWMETER
  etc: 
  ch_total_cnt: 2
  unit: FLOWMETER_USF500
  buadrate: _9600
  parity: none
  databit: bit8
  stopbit: bit1
  type: rs485
- address: 4
  use: true
  gui_display: false
  comport: 18
  name: 
  description: SUPPLY A PUMP CONTROLLER
  etc: 
  ch_total_cnt: 0
  unit: PUMP_CONTROLLER_PB12
  buadrate: _19200
  parity: odd
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 5
  use: true
  gui_display: false
  comport: 48
  name: 
  description: SUPPLY B PUMP CONTROLLER
  etc: 
  ch_total_cnt: 0
  unit: PUMP_CONTROLLER_PB12
  buadrate: _19200
  parity: odd
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 6
  use: false
  gui_display: false
  comport: 66
  name: 
  description: SPARE
  etc: 
  ch_total_cnt: 0
  unit: CONCENTRATION_CM210A_DC
  buadrate: _9600
  parity: none
  databit: bit8
  stopbit: bit1
  type: rs232_422
- address: 7
  use: true
  gui_display: false
  comport: 14
  name: 
  description: TEMP CONTROLLER
  etc: 
  ch_total_cnt: 2
  unit: TEMP_CONTROLLER_M74
  buadrate: _19200
  parity: even
  databit: bit8
  stopbit: bit1
  type: rs485
- address: 8
  use: false
  gui_display: false
  comport: 18
  name: 
  description: TEMP CONTROLLER
  etc: 
  ch_total_cnt: 0
  unit: TEMP_CONTROLLER_M74
  buadrate: _19200
  parity: even
  databit: bit8
  stopbit: bit1
  type: rs485
- address: 9
  use: false
  gui_display: false
  comport: 19
  name: 
  description: TEMP CONTROLLER
  etc: 
  ch_total_cnt: 0
  unit: TEMP_CONTROLLER_M74
  buadrate: _19200
  parity: even
  databit: bit8
  stopbit: bit1
  type: rs485