total_cnt: 35
unit_io:
- unit_type: ctc
  index: 0
  name: uCTC
  no: 0
- unit_type: pmc
  index: 1
  name: uPMC1
  no: 1
- unit_type: pmc
  index: 2
  name: uPMC2
  no: 2
- unit_type: pmc
  index: 3
  name: uPMC3
  no: 3
- unit_type: pmc
  index: 4
  name: uPMC4
  no: 4
- unit_type: pmc
  index: 5
  name: uPMC5
  no: 5
- unit_type: pmc
  index: 6
  name: uPMC6
  no: 6
- unit_type: pmc
  index: 7
  name: uPMC7
  no: 7
- unit_type: pmc
  index: 8
  name: uPMC8
  no: 8
- unit_type: pmc
  index: 9
  name: uPMC9
  no: 9
- unit_type: pmc
  index: 10
  name: uPMC10
  no: 10
- unit_type: pmc
  index: 11
  name: uPMC11
  no: 11
- unit_type: pmc
  index: 12
  name: uPMC12
  no: 12
- unit_type: spare
  index: 13
  name: spare13
  no: 13
- unit_type: spare
  index: 14
  name: spare14
  no: 14
- unit_type: cds
  index: 18
  name: uCDS18
  no: 18
- unit_type: cds
  index: 19
  name: uCDS19
  no: 19
- unit_type: cds
  index: 20
  name: uCDS20
  no: 20
- unit_type: cds
  index: 21
  name: uCDS21
  no: 21
- unit_type: cds
  index: 19
  name: uCDS22
  no: 22
- unit_type: cds
  index: 23
  name: uCDS23
  no: 23
- unit_type: spare
  index: 21
  name: spare21
  no: 21
- unit_type: spare
  index: 22
  name: spare22
  no: 22
- unit_type: spare
  index: 23
  name: spare23
  no: 23
- unit_type: spare
  index: 24
  name: spare24
  no: 24
- unit_type: spare
  index: 25
  name: spare25
  no: 25
- unit_type: spare
  index: 26
  name: spare26
  no: 26
- unit_type: spare
  index: 27
  name: spare27
  no: 27
- unit_type: ctc_io
  index: 30
  name: uDI
  no: 30
- unit_type: ctc_io
  index: 31
  name: uDO
  no: 31
- unit_type: ctc
  index: 32
  name: uAI
  no: 32
- unit_type: ctc_io
  index: 33
  name: uAO
  no: 33
- unit_type: spare
  index: 34
  name: spare34
  no: 34
- unit_type: spare
  index: 35
  name: spare35
  no: 35
- unit_type: spare
  index: 36
  name: spare36
  no: 36
