step_cnt: 2
ccss_cnt: 1
mixing_use: true
matching_file: ''
refill_use: true
ccss_info:
- name: H2O2
  use: true
  ccss_row: 1
  type: CCSS1
  chemical: H2O2
step_info:
- name: Not Use
  use: true
- name: Step 1
  use: true
mixing_data:
- 0
- 1
- 0
- 0
- 0
- 1
- 0
- 1
- 0
- 1
- 0
- 0
